main: fr.angrykiller.lightmsg.Main
name: LightMSG
version: 0.2
author: AngryKiller
database: false
commands:
    msg:
      description: Sends a private message to another player
      permission: lightmsg.send
    lightmsg:
      description: Shows the informations about the plugin