main: fr.angrykiller.lightmsg.Main
name: LightMSG
version: 0.2
author: AngryKiller
database: false
commands:
    msg:
      description: Envoie un message privé à un autre joueur
      permission: lightmsg.send